services:
  - type: web
    name: corrosion-inhibitor-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.index:app --bind 0.0.0.0:$PORT
    autoDeploy: true
